include:
  - _includes
  - _pages
  - .doctrees
  - _modules
  - _sources
  - _static
keep_files:
  - drugdiscovery/docs

sass:
  style: :compressed

theme: jekyll-theme-primer
  
title: MilaGraph
description: Project page of MilaGraph group

url: "https://deepgraphlearning.github.io"
baseurl: "/project"