include:
  - _includes
  - _pages

sass:
  style: :compressed

theme: jekyll-theme-primer
  
title: MilaGraph
description: Project page of MilaGraph group

url: "https://deepgraphlearning.github.io"
baseurl: "/project"